# Generated by Django 6.0.2 on 2026-03-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='to_address',
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_country',
            field=models.CharField(default='India', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_fullname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nick Name'),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_pincode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Place / Address Line 1'),
        ),
        migrations.AddField(
            model_name='letter',
            name='receiver_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_country',
            field=models.CharField(default='India', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_fullname',
            field=models.CharField(default='', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_nickname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nick Name'),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_pincode',
            field=models.CharField(default='', max_length=20, verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_place',
            field=models.CharField(default='', max_length=100, verbose_name='Place / Address Line 1'),
        ),
        migrations.AddField(
            model_name='letter',
            name='sender_state',
            field=models.CharField(default='', max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
