# Generated by Django 5.2.12 on 2026-03-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "letters",
            "0002_remove_letter_from_address_remove_letter_to_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
